// Bridge to the Fable-compiled F# core.
//
// `analyze` is generated by Fable from src/Core/Api.fs and emitted (as plain
// JavaScript with no type declarations) into ./core/. We give it a typed face
// here so the rest of the extension is fully type-checked.

import {
  analyze as fableAnalyze,
  catalog as fableCatalog,
  lint as fableLint,
} from "./core/Api.js";

/** One rendered block. Mirrors `Meticulous.Api.BlockView` in Api.fs.
 *  Which fields are meaningful depends on `kind`. */
export interface BlockView {
  kind:
    | "heading"
    | "prose"
    | "prop"
    | "claim"
    | "table"
    | "check"
    | "argument"
    | "proof"
    | "relations"
    | "relation"
    | "map"
    | "error";
  level: number;      // heading depth
  title: string;      // heading text / prose text / error message
  name: string;       // prop / claim / argument name
  gloss: string;      // prop meaning
  formula: string;    // rendered formula (minimal parens, Unicode operators)
  verdict: string;    // tautology | contradiction | contingent | equivalent | not-equivalent | valid | invalid
  atoms: string[];    // table column names (for arguments: counterexample columns)
  rows: boolean[][];  // one row per assignment (for arguments: counterexamples; modal: worlds)
  results: boolean[]; // the formula/conclusion value in each row (parallel to rows)
  actual: number;     // modal blocks: which row is the actual world (-1 = not modal)
  line: number;       // 1-based line, for error blocks
  premises: string[];   // argument premises, rendered
  conclusion: string;   // argument conclusion, rendered
  form: string;         // recognized valid form ("modus ponens"), or ""
  fallacy: string;      // recognized fallacy ("affirming the consequent"), or ""
  note: string;         // one-line explanation of the form/fallacy
  suggestion: string[]; // missing premises that would repair an invalid argument
  proof: string[][];    // derivation steps: [number, formula, justification]
  relations: string[][]; // from `analyze`: [left, relation, right]
}

export const analyze = fableAnalyze as unknown as (source: string) => BlockView[];

/** One inference-rule catalog entry. Mirrors `Meticulous.Api.FormView`. */
export interface FormView {
  name: string;        // machine name, e.g. "modus-ponens"
  title: string;       // display name, e.g. "modus ponens"
  aka: string;         // traditional alias ("" if none)
  note: string;        // one-line explanation
  premises: string[];  // patterns with metavariables, e.g. "φ → ψ"
  conclusion: string;
  isFallacy: boolean;
}

export const catalog = fableCatalog as unknown as () => FormView[];

/** A lint warning. Mirrors `Meticulous.Api.LintView`. */
export interface LintView {
  line: number; // 1-based
  message: string;
}

export const lint = fableLint as unknown as (source: string) => LintView[];
