// Bridge to the Fable-compiled F# core.
//
// `analyze` is generated by Fable from src/Core/Api.fs and emitted (as plain
// JavaScript with no type declarations) into ./core/. We give it a typed face
// here so the rest of the extension is fully type-checked.

import { analyze as fableAnalyze } from "./core/Api.js";

/** One rendered block. Mirrors `Meticulous.Api.BlockView` in Api.fs.
 *  Which fields are meaningful depends on `kind`. */
export interface BlockView {
  kind: "heading" | "prose" | "prop" | "claim" | "table" | "check" | "error";
  level: number;      // heading depth
  title: string;      // heading text / prose text / error message
  name: string;       // prop or claim name
  gloss: string;      // prop meaning
  formula: string;    // rendered formula (minimal parens, Unicode operators)
  verdict: string;    // tautology | contradiction | contingent | equivalent | not-equivalent
  atoms: string[];    // truth-table column names
  rows: boolean[][];  // one row per assignment: value for each atom
  results: boolean[]; // the formula's value in each row (parallel to rows)
  line: number;       // 1-based line, for error blocks
}

export const analyze = fableAnalyze as unknown as (source: string) => BlockView[];
